#!/usr/bin/env python3
import json
import shutil
import sys
from pathlib import Path


MARKER = ".armv7a_virt_full_overlay"


def die(message: str) -> None:
    raise SystemExit(message)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def replace_once(content: str, old: str, new: str, path: Path) -> str:
    if old not in content:
        die(f"expected text not found in {path}: {old!r}")
    return content.replace(old, new, 1)


def replace_all(content: str, replacements: list[tuple[str, str]]) -> str:
    for old, new in replacements:
        content = content.replace(old, new)
    return content


def set_config_bool(content: str, option: str) -> str:
    disabled = f"# {option} is not set"
    enabled = f"{option}=y"
    if disabled in content:
        return content.replace(disabled, enabled)
    if enabled not in content:
        return content + f"\n{enabled}"
    return content


def set_config_value(content: str, option: str, value: str) -> str:
    prefix = f"{option}="
    lines = content.splitlines()
    for index, line in enumerate(lines):
        if line.startswith(prefix):
            lines[index] = f"{option}={value}"
            return "\n".join(lines) + "\n"
    return content + f"\n{option}={value}"


def copy_owned_tree(src: Path, dst: Path) -> None:
    marker = dst / MARKER
    if dst.exists():
        if not marker.exists():
            die(f"refusing to replace non-overlay directory: {dst}")
        shutil.rmtree(dst)
    shutil.copytree(src, dst, symlinks=True)
    write_text(marker, "generated by overlays/armv7a_virt_full\n")


def load_json(path: Path) -> dict:
    return json.loads(read_text(path))


def dump_json(path: Path, data: dict) -> None:
    write_text(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def ensure_device_gni(root: Path) -> None:
    path = root / "device/qemu/common/virt_full/device.gni"
    content = read_text(path)
    if 'target_cpu == "arm")' not in content:
        content = replace_once(
            content,
            'virt_part_name = "qemu_virt_full"\nif (target_cpu == "x86_64") {',
            'virt_part_name = "qemu_virt_full"\n'
            'if (target_cpu == "arm") {\n'
            '  virt_subsystem_name = "device_armv7a_virt"\n'
            '  virt_part_name = "qemu_virt_full_armv7a"\n'
            '} else if (target_cpu == "x86_64") {',
            path,
        )
    if 'target_cpu == "arm") {\n  product_config_path = "//vendor/ohemu/virt"' not in content:
        content = replace_once(
            content,
            'product_config_path = "//vendor/${product_company}/${product_name}"\n'
            'if (target_cpu == "x86_64") {',
            'product_config_path = "//vendor/${product_company}/${product_name}"\n'
            'if (target_cpu == "arm") {\n'
            '  product_config_path = "//vendor/ohemu/virt"\n'
            '} else if (target_cpu == "x86_64") {',
            path,
        )
    write_text(path, content)


def ensure_hardware_group(root: Path) -> None:
    path = root / "device/qemu/common/virt_full/hardware/BUILD.gn"
    content = read_text(path)
    old = '''group("hardware_group") {
  deps = [
    "//device/qemu/common/virt_full/hardware/gpu:virtio",
    "//third_party/alsa-utils:entry",
    #"//third_party/mesa3d:zink_opengl",
    #"//third_party/expat:expat",
    #"//third_party/glmark2:glmark2",
    "//third_party/alsa-lib:libasound",
  ]
}
'''
    new = '''group("hardware_group") {
  deps = [
    "//third_party/alsa-utils:entry",
    #"//third_party/mesa3d:zink_opengl",
    #"//third_party/expat:expat",
    #"//third_party/glmark2:glmark2",
    "//third_party/alsa-lib:libasound",
  ]

  # The checked-in GPU binaries only cover arm64 and x86_64. Build Mesa's
  # kms_swrast driver from source for the armv7a QEMU product.
  if (target_cpu == "arm") {
    deps += [ "//third_party/mesa3d/ohos:mesa3d_all_libs" ]
  } else {
    deps += [ "//device/qemu/common/virt_full/hardware/gpu:virtio" ]
  }
}
'''
    if old in content:
        content = content.replace(old, new, 1)
        write_text(path, content)
        return
    previous = '''  # The virtio GPU prebuilt directory currently only contains arm64 and x86_64
  # Mesa/GL userspace libraries. armv7a uses RenderService's supported CPU
  # rendering path, so do not install foreign-architecture GPU binaries.
  if (target_cpu != "arm") {
    deps += [ "//device/qemu/common/virt_full/hardware/gpu:virtio" ]
  }
'''
    replacement = '''  # The checked-in GPU binaries only cover arm64 and x86_64. Build Mesa's
  # kms_swrast driver from source for the armv7a QEMU product.
  if (target_cpu == "arm") {
    deps += [ "//third_party/mesa3d/ohos:mesa3d_all_libs" ]
  } else {
    deps += [ "//device/qemu/common/virt_full/hardware/gpu:virtio" ]
  }
'''
    if previous in content:
        write_text(path, content.replace(previous, replacement, 1))
        return
    if 'deps += [ "//third_party/mesa3d/ohos:mesa3d_all_libs" ]' in content:
        return
    die(f"expected hardware group not found in {path}")


def restore_display_device_upstream(root: Path) -> None:
    path = root / (
        "device/qemu/common/virt_full/hardware/display/src/display_device/"
        "hdi_device_interface.cpp"
    )
    content = read_text(path)
    upstream = '''    if (!drmDevice) {
        DISPLAY_LOGE("can not create drm device");
    }
    ret = drmDevice->Init();
'''
    previous_experiment = '''    if (!drmDevice) {
        DISPLAY_LOGE("can not create drm device");
        return devices;
    }
    ret = drmDevice->Init();
'''
    if previous_experiment in content:
        write_text(path, content.replace(previous_experiment, upstream, 1))
    elif upstream not in content:
        die(f"expected upstream DRM device block not found in {path}")


def ensure_power_dialog_upstream_config(root: Path) -> None:
    path = root / "base/powermgr/power_manager/power_dialog/build-profile.json5"
    content = read_text(path)
    previous = '"compileSdkVersion": 26'
    current = '"compileSdkVersion": "26.0.0"'
    if previous in content:
        write_text(path, content.replace(previous, current, 1))
    elif current not in content:
        die(f"expected OpenHarmony power dialog SDK configuration not found in {path}")

    path = root / "base/powermgr/power_manager/power_dialog/hvigor/hvigor-config.json5"
    content = read_text(path)
    hvigor_6 = '''{
  "hvigorVersion": "6.0.0",
  "dependencies": {
    "@ohos/hvigor-ohos-plugin": "6.0.0"
  }
}'''
    model_6 = '''{
  "modelVersion": "6.0.0",
  "dependencies": {
  }
}'''
    hvigor_4 = '''{
  "hvigorVersion": "4.0.9",
  "dependencies": {
    "@ohos/hvigor-ohos-plugin": "4.0.9"
  }
}'''
    if hvigor_4 in content:
        write_text(path, content.replace(hvigor_4, model_6, 1))
    elif hvigor_6 in content:
        write_text(path, content.replace(hvigor_6, model_6, 1))
    elif model_6 not in content:
        die(f"expected power dialog Hvigor configuration not found in {path}")


def ensure_armv7a_mesa(root: Path) -> None:
    path = root / "third_party/mesa3d/ohos/BUILD.gn"
    content = read_text(path)
    new_vars = '''if (product_name == "armv7a_virt") {
  mesa3d_egl_name = "libEGL.so.1.0.0"
  mesa3d_egl_symlinks = [ "libEGL_impl.so" ]
  mesa3d_gles1_symlinks = [ "libGLESv1_impl.so" ]
  mesa3d_gles2_symlinks = [
    "libGLESv2_impl.so",
    "libGLESv3_impl.so",
  ]
  mesa3d_gallium_name = "kms_swrast_dri.so"
  mesa3d_gallium_symlinks = [ "swrast_dri.so" ]
  mesa3d_optional_lib_items = [
    [
      "libglapi.so.0.0.0",
      [
        "libglapi.so",
        "libglapi.so.0",
      ],
    ],
  ]
  mesa3d_subsystem_name = "device_armv7a_virt"
  mesa3d_part_name = "qemu_virt_full_armv7a"
} else {
  mesa3d_egl_name = "libEGL.so.1.0.0"
  mesa3d_egl_symlinks = [
    "libEGL.so",
    "libEGL.so.1",
    "libEGL_impl.so",
  ]
  mesa3d_gles1_symlinks = [
    "libGLESv1_CM.so",
    "libGLESv1_CM.so.1",
    "libGLESv1_impl.so",
  ]
  mesa3d_gles2_symlinks = [
    "libGLESv2.so",
    "libGLESv2.so.2",
    "libGLESv3.so",
    "libGLESv2_impl.so",
    "libGLESv3_impl.so",
  ]
  mesa3d_gallium_name = "libgallium_dri.so"
  mesa3d_gallium_symlinks = [ "panfrost_dri.so" ]
  mesa3d_optional_lib_items = [
    [
      "libglapi.so.0.0.0",
      [
        "libglapi.so",
        "libglapi.so.0",
      ],
    ],
  ]
  mesa3d_subsystem_name = "rockchip_products"
  mesa3d_part_name = "rockchip_products"
}
'''
    vars_start_marker = 'mesa3d_libs_dir = "$root_build_dir/packages/phone/mesa3d"\n'
    vars_end_marker = "\nmesa3d_all_lib_items = ["
    vars_start = content.find(vars_start_marker)
    vars_end = content.find(vars_end_marker, vars_start + len(vars_start_marker))
    if vars_start < 0 or vars_end < 0:
        die(f"expected Mesa library configuration markers not found in {path}")
    vars_start += len(vars_start_marker)
    content = content[:vars_start] + "\n" + new_vars + content[vars_end:]

    new_items = '''mesa3d_all_lib_items = [
  [
    mesa3d_egl_name,
    mesa3d_egl_symlinks,
  ],
  [
    "libgbm.so.1.0.0",
    [
      "libgbm.so",
      "libgbm.so.1",
    ],
  ],
] + mesa3d_optional_lib_items + [
  [
    "libGLESv1_CM.so.1.1.0",
    mesa3d_gles1_symlinks,
  ],
  [
    "libGLESv2.so.2.0.0",
    mesa3d_gles2_symlinks,
  ],
  [
    mesa3d_gallium_name,
    mesa3d_gallium_symlinks,
  ],
]
'''
    items_start = content.find("mesa3d_all_lib_items = [")
    items_end = content.find('\naction("mesa3d_build") {', items_start)
    if items_start < 0 or items_end < 0:
        die(f"expected Mesa library list boundaries not found in {path}")
    content = content[:items_start] + new_items + content[items_end + 1:]

    build_targets = '''action("mesa3d_build") {
  script = "build_mesa3d.py"
  deps = [ "//third_party/expat:expat" ]
  if (product_name != "armv7a_virt") {
    deps += [ "//foundation/graphic/graphic_2d:libsurface" ]
  }
  if (product_name == "armv7a_virt") {
    script = "//device/qemu/arm_virt/linux_full_armv7a/build_armv7a_mesa.py"
    deps += [ "//third_party/libdrm:libdrm" ]
    external_deps = [
      "graphic_surface:surface",
      "hilog:libhilog",
    ]
  }
  outputs = []
  foreach(item, mesa3d_all_lib_items) {
    outputs += [ "$mesa3d_libs_dir/${item[0]}" ]
  }
  args = [ rebase_path(root_build_dir) ]
}

mesa3d_all_lib_deps = []

foreach(item, mesa3d_all_lib_items) {
  name = item[0]
  ohos_prebuilt_shared_library(name) {
    source = "$mesa3d_libs_dir/$name"
    deps = [ ":mesa3d_build" ]
    if (item[1] != []) {
      symlink_target_name = item[1]
    }
    install_enable = true
    install_images = [ system_base_dir ]
    subsystem_name = mesa3d_subsystem_name
    part_name = mesa3d_part_name
    if (product_name == "armv7a_virt") {
      module_install_dir = "lib"
    }
  }
  mesa3d_all_lib_deps += [ ":$name" ]
}

group("mesa3d_all_libs") {
  deps = mesa3d_all_lib_deps
}
'''
    action_start = content.find('action("mesa3d_build") {')
    group_start = content.find('group("mesa3d_all_libs") {', action_start)
    group_end = content.find("\n}", group_start)
    if action_start < 0 or group_start < 0 or group_end < 0:
        die(f"expected Mesa build target boundaries not found in {path}")
    group_end += len("\n}")
    content = content[:action_start] + build_targets + content[group_end:]
    write_text(path, content)

    # The QEMU Mesa baseline is extracted from OpenHarmony's GitHub history by
    # the armv7a builder. Remove earlier Mesa 25 KMS experiments from reused
    # checkouts so the active master tree remains unchanged.
    options_path = root / "third_party/mesa3d/meson_options.txt"
    content = read_text(options_path)
    option = '''option(
  'ohos-kms-drm',
  type : 'boolean',
  value : false,
  description : 'Keep DRM/KMS enabled for OpenHarmony virtual devices',
)

'''
    if option in content:
        write_text(options_path, content.replace(option, "", 1))

    meson_path = root / "third_party/mesa3d/meson.build"
    content = read_text(meson_path)
    modified = '''if with_platform_ohos
  pre_args += '-DVK_USE_PLATFORM_OHOS=1'
  if not get_option('ohos-kms-drm')
    system_has_kms_drm = false
  endif
endif
'''
    upstream = '''if with_platform_ohos
  pre_args += '-DVK_USE_PLATFORM_OHOS=1'
  system_has_kms_drm = false
endif
'''
    if modified in content:
        write_text(meson_path, content.replace(modified, upstream, 1))

    egl_meson_path = root / "third_party/mesa3d/src/egl/meson.build"
    content = read_text(egl_meson_path)
    modified = '''  if with_gbm and not with_platform_android and \
      (not with_platform_ohos or get_option('ohos-kms-drm'))
    files_egl += files('drivers/dri2/platform_drm.c')
    link_for_egl += libgbm
    incs_for_egl += [inc_gbm, include_directories('../gbm/main')]
    deps_for_egl += dep_libdrm
  endif
'''
    upstream = '''  if with_gbm and not with_platform_android and not with_platform_ohos
    files_egl += files('drivers/dri2/platform_drm.c')
    link_for_egl += libgbm
    incs_for_egl += [inc_gbm, include_directories('../gbm/main')]
    deps_for_egl += dep_libdrm
  endif
'''
    if modified in content:
        content = content.replace(modified, upstream, 1)
    modified = '''  if with_platform_ohos
    deps_for_egl += [dependency('libsurface')]
    files_egl += files('drivers/dri2/platform_ohos.c')
    if get_option('ohos-kms-drm')
      c_args_for_egl += '-DOHOS_KMS_SWRAST'
    endif
  endif
'''
    upstream = '''  if with_platform_ohos
    deps_for_egl += [dependency('libsurface')]
    files_egl += files('drivers/dri2/platform_ohos.c')
  endif
'''
    if modified in content:
        content = content.replace(modified, upstream, 1)
    write_text(egl_meson_path, content)

    ohos_platform_path = root / (
        "third_party/mesa3d/src/egl/drivers/dri2/platform_ohos.c"
    )
    content = read_text(ohos_platform_path)
    content = content.replace('#include "loader.h"\n', "", 1)
    modified = '''static bool
load_zink_kopper(_EGLDisplay *disp)
{
   struct dri2_egl_display *dri2_dpy = dri2_egl_display(disp);

#ifdef OHOS_KMS_SWRAST
   dri2_dpy->fd_render_gpu = loader_open_device("/dev/dri/card0");
   if (dri2_dpy->fd_render_gpu < 0)
      return false;
   dri2_dpy->fd_display_gpu = dri2_dpy->fd_render_gpu;
   dri2_dpy->driver_name = strdup("kms_swrast");
#else
   dri2_dpy->fd_render_gpu = -1;
   dri2_dpy->fd_display_gpu = -1;
   dri2_dpy->driver_name = strdup("zink");
#endif
   if (!dri2_dpy->driver_name)
      return false;

   if (!dri2_load_driver(disp)) {
      free(dri2_dpy->driver_name);
      dri2_dpy->driver_name = NULL;
      return false;
   }

   dri2_dpy->loader_extensions = image_loader_extensions;

   return true;
}
'''
    upstream = '''static bool
load_zink_kopper(_EGLDisplay *disp)
{
   struct dri2_egl_display *dri2_dpy = dri2_egl_display(disp);

   dri2_dpy->fd_render_gpu = -1;
   dri2_dpy->fd_display_gpu = -1;
   dri2_dpy->driver_name = strdup("zink");
   if (!dri2_dpy->driver_name)
      return false;

   if (!dri2_load_driver(disp)) {
      free(dri2_dpy->driver_name);
      dri2_dpy->driver_name = NULL;
      return false;
   }

   dri2_dpy->loader_extensions = image_loader_extensions;

   return true;
}
'''
    if modified in content:
        content = content.replace(modified, upstream, 1)
    modified = '''static const __DRIextension *image_loader_extensions[] = {
   &image_lookup_extension.base,
   &kopper_loader_extension.base,
   &swrast_loader_extension.base,
   &dri2_loader_extension.base,
#ifdef OHOS_KMS_SWRAST
   &use_invalidate.base,
#endif
   NULL,
};
'''
    upstream = '''static const __DRIextension *image_loader_extensions[] = {
   &image_lookup_extension.base,
   &kopper_loader_extension.base,
   &swrast_loader_extension.base,
   &dri2_loader_extension.base,
   NULL,
};
'''
    if modified in content:
        content = content.replace(modified, upstream, 1)
    modified = '''EGLBoolean
dri2_initialize_ohos(_EGLDisplay *disp)
{
   const char *err;
   struct dri2_egl_display *dri2_dpy = dri2_egl_display(disp);
'''
    upstream = '''EGLBoolean
dri2_initialize_ohos(_EGLDisplay *disp)
{
   const char *err;
   struct dri2_egl_display *dri2_dpy = dri2_display_create(disp);
   if (!dri2_dpy)
      return EGL_FALSE;
'''
    if modified in content:
        content = content.replace(modified, upstream, 1)
    modified = '''cleanup:
   return _eglError(EGL_NOT_INITIALIZED, err);
}
'''
    upstream = '''cleanup:
   dri2_display_destroy(disp);
   return _eglError(EGL_NOT_INITIALIZED, err);
}
'''
    if modified in content:
        content = content.replace(modified, upstream, 1)
    write_text(ohos_platform_path, content)

    dri_symbols_path = root / "third_party/mesa3d/src/gallium/targets/dri/dri.sym.in"
    content = read_text(dri_symbols_path)
    content = content.replace(
        "                __emutls_v._mesa_glapi_tls_Context;\n",
        "",
    )
    content = content.replace(
        "                __emutls_v._mesa_glapi_tls_Dispatch;\n",
        "",
    )
    write_text(dri_symbols_path, content)


def restore_musl_dlopen_cleanup(root: Path) -> None:
    path = root / "third_party/musl/ldso/linux/dynlink.c"
    content = read_text(path)
    upstream = '''\t\t\tif (p->parents) {
\t\t\t\tfree(p->parents);
\t\t\t}
\t\t\tfree_reloc_can_search_dso(p);
\t\t}
\t\tfor (p=orig_tail->next; p; p=next) {
\t\t\tnext = p->next;
\t\t\tfree(p);
'''
    previous_experiment = '''\t\t\tfree_reloc_can_search_dso(p);
\t\t}
\t\tfor (p=orig_tail->next; p; p=next) {
\t\t\tnext = p->next;
\t\t\tfree(p->parents);
\t\t\tfree(p);
'''
    if previous_experiment in content:
        write_text(path, content.replace(previous_experiment, upstream, 1))
    elif upstream not in content:
        die(f"expected musl dlopen cleanup block not found in {path}")


def ensure_armv7a_kernel_config(root: Path) -> None:
    # QEMU virt has no DSA switch hardware. The arm64/riscv64 virt full
    # defconfigs already keep DSA disabled; armv7a must do the same because the
    # current linux-6.6 tree lacks net/dsa/conduit.h while CONFIG_NET_DSA=m.
    #
    # The standard-system init path also expects the same runtime kernel
    # features present in the maintained arm64/x86_64 full QEMU configs:
    # pids/cpuacct cgroups, namespaces, SELinux LSM, ext4 security xattrs, and
    # the DRM/input drivers used by QEMU's MMIO virtio devices.
    for relative in (
        "device/qemu/common/virt_full/kernel/arm_virt_defconfig",
        "device/qemu/common/virt_full/kernel/configs/arm_virt_defconfig",
    ):
        path = root / relative
        content = read_text(path)
        replacements = [
            ("CONFIG_NET_DSA=m", "# CONFIG_NET_DSA is not set"),
            ("CONFIG_NET_DSA_TAG_NONE=m", "# CONFIG_NET_DSA_TAG_NONE is not set"),
            ("CONFIG_NET_DSA_TAG_BRCM_COMMON=m", "# CONFIG_NET_DSA_TAG_BRCM_COMMON is not set"),
            ("CONFIG_NET_DSA_TAG_BRCM=m", "# CONFIG_NET_DSA_TAG_BRCM is not set"),
            ("CONFIG_NET_DSA_TAG_BRCM_LEGACY=m", "# CONFIG_NET_DSA_TAG_BRCM_LEGACY is not set"),
            ("CONFIG_NET_DSA_TAG_BRCM_PREPEND=m", "# CONFIG_NET_DSA_TAG_BRCM_PREPEND is not set"),
            ("CONFIG_NET_DSA_BCM_SF2=m", "# CONFIG_NET_DSA_BCM_SF2 is not set"),
        ]
        new_content = replace_all(content, replacements)
        for option in (
            "CONFIG_CGROUP_CPUACCT",
            "CONFIG_CGROUP_HUGETLB",
            "CONFIG_CGROUP_PIDS",
            "CONFIG_PSI",
            "CONFIG_NAMESPACES",
            "CONFIG_UTS_NS",
            "CONFIG_IPC_NS",
            "CONFIG_USER_NS",
            "CONFIG_PID_NS",
            "CONFIG_NET_NS",
            "CONFIG_EXT4_FS_POSIX_ACL",
            "CONFIG_EXT4_FS_SECURITY",
            "CONFIG_DRM",
            "CONFIG_DRM_KMS_HELPER",
            "CONFIG_DRM_FBDEV_EMULATION",
            "CONFIG_DRM_GEM_SHMEM_HELPER",
            "CONFIG_DRM_VIRTIO_GPU",
            "CONFIG_FB",
            "CONFIG_SYNC_FILE",
            "CONFIG_VIRTIO_BALLOON",
            "CONFIG_VIRTIO_INPUT",
            "CONFIG_VIRTIO_MMIO",
        ):
            new_content = set_config_bool(new_content, option)
        new_content = set_config_bool(new_content, "CONFIG_DEFAULT_SECURITY_SELINUX")
        new_content = set_config_value(
            new_content,
            "CONFIG_LSM",
            '"selinux,lockdown,yama,loadpin,safesetid,integrity"',
        )
        if new_content != content:
            write_text(path, new_content)


def ensure_armv7a_libvpx_config(root: Path) -> None:
    build_gn = root / "third_party/libvpx/BUILD.gn"
    build_sh = root / "third_party/libvpx/build.sh"

    content = read_text(build_gn)
    old = """  if (is_vpx_x86_64) {
    outputs += [
      "$code_dir/vp8_rtcd.h",
      "$code_dir/vp9_rtcd.h",
      "$code_dir/vpx_dsp_rtcd.h",
      "$code_dir/vpx_scale_rtcd.h",
    ]
  }
"""
    new = """  if (is_vpx_x86_64) {
    outputs += [
      "$code_dir/vp8_rtcd.h",
      "$code_dir/vp9_rtcd.h",
      "$code_dir/vpx_dsp_rtcd.h",
      "$code_dir/vpx_scale_rtcd.h",
    ]
  } else if (is_vpx_arm) {
    outputs += [ "$code_dir/vpx_scale_rtcd.h" ]
  }
"""
    if old in content:
        write_text(build_gn, content.replace(old, new))
    elif new not in content:
        die(f"expected libvpx outputs block not found in {build_gn}")

    content = read_text(build_sh)
    marker = """if [ "$CPU" == "x86_64" ]; then
"""
    insert = """if [ "$CPU" == "arm" ]; then
  cat > rtcd_config.mk <<'EOF'
CONFIG_RUNTIME_CPU_DETECT=no
CONFIG_VP8_DECODER=yes
CONFIG_VP8_ENCODER=no
CONFIG_VP9=yes
CONFIG_VP9_DECODER=yes
CONFIG_VP9_ENCODER=no
CONFIG_VP9_HIGHBITDEPTH=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_POSTPROC=no
CONFIG_MULTITHREAD=yes
CONFIG_WEBM_IO=no
CONFIG_LIBYUV=no
EOF

  perl build/make/rtcd.pl --arch=armv7 --sym=vpx_scale_rtcd \\
      --config=rtcd_config.mk vpx_scale/vpx_scale_rtcd.pl \\
      > "$OUTPUT_DIR/vpx_scale_rtcd.h"
  rm -f rtcd_config.mk
fi

"""
    previous_insert = insert.replace(
        '''  perl build/make/rtcd.pl --arch=armv7 --sym=vpx_scale_rtcd \\
      --config=rtcd_config.mk vpx_scale/vpx_scale_rtcd.pl \\
      > "$OUTPUT_DIR/vpx_scale_rtcd.h"
  rm -f rtcd_config.mk
''',
        '''  perl build/make/rtcd.pl --arch=armv7 --sym=vpx_scale_rtcd \\
      --config=rtcd_config.mk vpx_scale/vpx_scale_rtcd.pl > vpx_scale_rtcd.h
  cp vpx_scale_rtcd.h "$OUTPUT_DIR/"
  rm -f rtcd_config.mk vpx_scale_rtcd.h
''',
    )
    if previous_insert in content:
        write_text(build_sh, content.replace(previous_insert, insert, 1))
    elif insert not in content:
        if marker not in content:
            die(f"expected libvpx x86_64 block marker not found in {build_sh}")
        write_text(build_sh, content.replace(marker, insert + marker))


def ensure_whitelist(root: Path) -> None:
    path = root / "build/subsystem_components_whitelist.json"
    whitelist = load_json(path)
    whitelist["device_armv7a_virt"] = "device_armv7a_virt"
    whitelist["product_armv7a_virt"] = "product_armv7a_virt"
    dump_json(path, whitelist)


def create_device(root: Path) -> None:
    src = root / "device/qemu/arm_virt/linux_full"
    dst = root / "device/qemu/arm_virt/linux_full_armv7a"
    copy_owned_tree(src, dst)

    write_text(
        dst / "BUILD.gn",
        '''# Copyright (C) 2024 Institute of Software, Chinese Academy of Sciences .

group("qemu-armv7a-linux-full-group") {
  deps = [ "//device/qemu/common/virt_full:virt_group" ]
}
''',
    )
    write_text(
        dst / "config.gni",
        '''# Copyright (c) 2022 Huawei Device Co., Ltd.

board_arch = "armv7-a"
board_cpu = "cortex-a7"
board_toolchain_type = "clang"
board_fpu = "neon-vfpv4"
''',
    )
    mesa_builder = dst / "build_armv7a_mesa.py"
    shutil.copy2(
        Path(__file__).with_name("build_armv7a_mesa.py"),
        mesa_builder,
    )
    mesa_builder.chmod(0o755)

    bundle = load_json(dst / "bundle.json")
    bundle["name"] = "@ohos/qemu_armv7a_linux_full_device"
    bundle["description"] = "device part definition for qemu armv7a linux full"
    bundle["segment"]["destPath"] = "device/qemu/arm_virt/linux_full_armv7a"
    component = bundle["component"]
    component["name"] = "qemu_virt_full_armv7a"
    component["subsystem"] = "device_armv7a_virt"
    component["build"]["sub_component"] = [
        "//drivers/peripheral/camera/vdi_base/usb_camera:usb_camera_vdi_impl",
        "//device/qemu/arm_virt/linux_full_armv7a:qemu-armv7a-linux-full-group",
    ]
    dump_json(dst / "bundle.json", bundle)


def create_product(root: Path) -> None:
    src = root / "vendor/ohemu/qemu_arm64_linux_full"
    dst = root / "vendor/ohemu/qemu_armv7a_linux_full"
    copy_owned_tree(src, dst)

    common_src = root / "vendor/ohemu/virt/virt_common.json"
    common_dst = root / "vendor/ohemu/virt/virt_common_armv7a.json"
    common = load_json(common_src)
    for subsystem in common.get("subsystems", []):
        if subsystem.get("subsystem") != "device_arm64_virt":
            continue
        subsystem["subsystem"] = "device_armv7a_virt"
        for component in subsystem.get("components", []):
            if component.get("component") == "qemu_virt_full":
                component["component"] = "qemu_virt_full_armv7a"
        break
    else:
        die(f"expected device_arm64_virt subsystem in {common_src}")
    dump_json(common_dst, common)

    config = load_json(dst / "config.json")
    config["product_name"] = "armv7a_virt"
    config["device_build_path"] = "device/qemu/arm_virt/linux_full_armv7a"
    config["target_cpu"] = "arm"
    config["target_os"] = "ohos"
    config["board"] = "armv7a_virt"
    config["inherit"] = [
        "productdefine/common/inherit/rich.json",
        "productdefine/common/inherit/chipset_common.json",
        "vendor/ohemu/virt/virt_common_armv7a.json",
    ]
    dump_json(dst / "config.json", config)

    bundle_path = dst / "bundle.json"
    bundle = load_json(bundle_path)
    bundle["name"] = "@ohos/qemu_armv7a_linux_full_product"
    bundle["description"] = "product part definition for qemu armv7a linux full"
    bundle["segment"]["destPath"] = "vendor/ohemu/qemu_armv7a_linux_full"
    component = bundle["component"]
    component["name"] = "product_armv7a_virt"
    component["subsystem"] = "product_armv7a_virt"
    component["build"]["sub_component"] = [
        "//vendor/ohemu/qemu_armv7a_linux_full/power_config:power_mode_config"
    ]
    dump_json(bundle_path, bundle)

    power_path = dst / "power_config/BUILD.gn"
    power = replace_all(
        read_text(power_path),
        [
            ("product_arm64_virt", "product_armv7a_virt"),
            ("qemu_arm64_linux_full", "qemu_armv7a_linux_full"),
        ],
    )
    write_text(power_path, power)

    write_text(dst / "qemu_run.sh", armv7a_qemu_run())


def armv7a_qemu_run() -> str:
    return r'''#!/bin/bash

# Experimental armv7a full-system QEMU launcher generated by ohos-qemu.

set -euo pipefail

OHOS_IMG="${OHOS_IMG:-out/armv7a_virt/packages/phone/images}"
DISPLAY_TYPE="${QEMU_DISPLAY:-none}"

ACCEL_SUPPORT=$(qemu-system-arm -accel help 2>&1 | grep "Accelerators supported" || true)
if [ -e /dev/kvm ] && [ -r /dev/kvm ] && echo "$ACCEL_SUPPORT" | grep -q "kvm"; then
    ACCEL_ARGS="-accel kvm"
    echo "KVM acceleration enabled." >&2
else
    ACCEL_ARGS="-accel tcg,thread=multi"
    echo "Hardware acceleration not available, using TCG software emulation." >&2
fi

NET_ARGS=(
    -netdev user,id=net0,hostfwd=tcp::5555-:5555
    -device virtio-net-device,netdev=net0,mac=12:22:33:44:55:67
)

case "${DISPLAY_TYPE}" in
    none)
        DISPLAY_ARGS="-device virtio-gpu-pci,xres=800,yres=500 -display none -monitor none -serial file:/dev/fd/1"
        ;;
    vnc)
        DISPLAY_ARGS="-device virtio-gpu-pci,xres=800,yres=500 -vnc :21"
        echo "Display: VNC on port 5921"
        ;;
    sdl|*)
        DISPLAY_ARGS="-device virtio-gpu-pci,xres=800,yres=500 -display sdl,gl=off"
        echo "Display: SDL"
        ;;
esac

QEMU_CMD="qemu-system-arm ${ACCEL_ARGS} \
-M virt,highmem=off \
-cpu cortex-a7 \
-smp 4 \
-m 3072 \
-kernel ${OHOS_IMG}/zImage \
-initrd ${OHOS_IMG}/ramdisk.img \
${DISPLAY_ARGS} \
-device virtio-mouse-pci \
-device virtio-keyboard-pci \
-k en-us \
-rtc base=localtime,clock=host \
${NET_ARGS[@]} \
-drive if=none,file=${OHOS_IMG}/updater.img,format=raw,id=updater -device virtio-blk-device,drive=updater,serial=updater \
-drive if=none,file=${OHOS_IMG}/system.img,format=raw,id=system -device virtio-blk-device,drive=system,serial=system \
-drive if=none,file=${OHOS_IMG}/vendor.img,format=raw,id=vendor -device virtio-blk-device,drive=vendor,serial=vendor \
-drive if=none,file=${OHOS_IMG}/sys_prod.img,format=raw,id=sys_prod -device virtio-blk-device,drive=sys_prod,serial=sys_prod \
-drive if=none,file=${OHOS_IMG}/chip_prod.img,format=raw,id=chip_prod -device virtio-blk-device,drive=chip_prod,serial=chip_prod \
-drive if=none,file=${OHOS_IMG}/userdata.img,format=raw,id=userdata -device virtio-blk-device,drive=userdata,serial=userdata \
-append \" \
default_boot_device=a003e00.virtio_mmio \
sn=0023456789 \
ip=dhcp \
loglevel=4 \
console=ttyAMA0,115200 \
init=/bin/init ohos.boot.hardware=virt \
root=/dev/ram0 rw \
ohos.required_mount.system=/dev/block/vde@/usr@ext4@ro,barrier=1@wait,required \
ohos.required_mount.vendor=/dev/block/vdd@/vendor@ext4@ro,barrier=1@wait,required \
ohos.required_mount.sys_prod=/dev/block/vdc@/sys_prod@ext4@rw,barrier=1@wait,required \
ohos.required_mount.chip_prod=/dev/block/vdb@/chip_prod@ext4@rw,barrier=1@wait,required \
ohos.required_mount.data=/dev/block/vda@/data@ext4@nosuid,nodev,noatime,barrier=1,data=ordered,noauto_da_alloc@wait,required,reservedsize=104857600\""

echo "=== QEMU Command ===" >&2
echo "$QEMU_CMD" >&2
echo "====================" >&2
eval "$QEMU_CMD"
'''


def main() -> None:
    if len(sys.argv) != 2:
        die("usage: apply.py OHOS_ROOT")
    root = Path(sys.argv[1]).resolve()
    if not (root / "build.sh").exists():
        die(f"not an OpenHarmony checkout: {root}")

    create_device(root)
    create_product(root)
    ensure_device_gni(root)
    ensure_hardware_group(root)
    restore_display_device_upstream(root)
    ensure_power_dialog_upstream_config(root)
    ensure_armv7a_mesa(root)
    restore_musl_dlopen_cleanup(root)
    ensure_armv7a_kernel_config(root)
    ensure_armv7a_libvpx_config(root)
    ensure_whitelist(root)
    print("armv7a_virt full overlay applied")


if __name__ == "__main__":
    main()
