#!/usr/bin/env python3
import json
import shutil
import sys
from pathlib import Path


MARKER = ".armv7a_virt_full_overlay"


def die(message: str) -> None:
    raise SystemExit(message)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def replace_once(content: str, old: str, new: str, path: Path) -> str:
    if old not in content:
        die(f"expected text not found in {path}: {old!r}")
    return content.replace(old, new, 1)


def replace_all(content: str, replacements: list[tuple[str, str]]) -> str:
    for old, new in replacements:
        content = content.replace(old, new)
    return content


def copy_owned_tree(src: Path, dst: Path) -> None:
    marker = dst / MARKER
    if dst.exists():
        if not marker.exists():
            die(f"refusing to replace non-overlay directory: {dst}")
        shutil.rmtree(dst)
    shutil.copytree(src, dst, symlinks=True)
    write_text(marker, "generated by overlays/armv7a_virt_full\n")


def load_json(path: Path) -> dict:
    return json.loads(read_text(path))


def dump_json(path: Path, data: dict) -> None:
    write_text(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def ensure_device_gni(root: Path) -> None:
    path = root / "device/qemu/common/virt_full/device.gni"
    content = read_text(path)
    if 'target_cpu == "arm")' not in content:
        content = replace_once(
            content,
            'virt_part_name = "qemu_virt_full"\nif (target_cpu == "x86_64") {',
            'virt_part_name = "qemu_virt_full"\n'
            'if (target_cpu == "arm") {\n'
            '  virt_subsystem_name = "device_armv7a_virt"\n'
            '  virt_part_name = "qemu_virt_full_armv7a"\n'
            '} else if (target_cpu == "x86_64") {',
            path,
        )
    if 'target_cpu == "arm") {\n  product_config_path = "//vendor/ohemu/virt"' not in content:
        content = replace_once(
            content,
            'product_config_path = "//vendor/${product_company}/${product_name}"\n'
            'if (target_cpu == "x86_64") {',
            'product_config_path = "//vendor/${product_company}/${product_name}"\n'
            'if (target_cpu == "arm") {\n'
            '  product_config_path = "//vendor/ohemu/virt"\n'
            '} else if (target_cpu == "x86_64") {',
            path,
        )
    write_text(path, content)


def ensure_hardware_group(root: Path) -> None:
    path = root / "device/qemu/common/virt_full/hardware/BUILD.gn"
    content = read_text(path)
    old = '''group("hardware_group") {
  deps = [
    "//device/qemu/common/virt_full/hardware/gpu:virtio",
    "//third_party/alsa-utils:entry",
    #"//third_party/mesa3d:zink_opengl",
    #"//third_party/expat:expat",
    #"//third_party/glmark2:glmark2",
    "//third_party/alsa-lib:libasound",
  ]
}
'''
    new = '''group("hardware_group") {
  deps = [
    "//third_party/alsa-utils:entry",
    #"//third_party/mesa3d:zink_opengl",
    #"//third_party/expat:expat",
    #"//third_party/glmark2:glmark2",
    "//third_party/alsa-lib:libasound",
  ]

  # The virtio GPU prebuilt directory currently only contains arm64 and x86_64
  # Mesa/GL userspace libraries. Keep armv7a on the standard system stack, but
  # avoid depending on a GPU prebuilt that has no 32-bit ARM payload.
  if (target_cpu != "arm") {
    deps += [ "//device/qemu/common/virt_full/hardware/gpu:virtio" ]
  }
}
'''
    if old in content:
        content = content.replace(old, new, 1)
        write_text(path, content)
        return
    if 'if (target_cpu != "arm") {' in content:
        return
    die(f"expected hardware group not found in {path}")


def ensure_whitelist(root: Path) -> None:
    path = root / "build/subsystem_components_whitelist.json"
    whitelist = load_json(path)
    whitelist["device_armv7a_virt"] = "device_armv7a_virt"
    whitelist["product_armv7a_virt"] = "product_armv7a_virt"
    dump_json(path, whitelist)


def create_device(root: Path) -> None:
    src = root / "device/qemu/arm_virt/linux_full"
    dst = root / "device/qemu/arm_virt/linux_full_armv7a"
    copy_owned_tree(src, dst)

    write_text(
        dst / "BUILD.gn",
        '''# Copyright (C) 2024 Institute of Software, Chinese Academy of Sciences .

group("qemu-armv7a-linux-full-group") {
  deps = [ "//device/qemu/common/virt_full:virt_group" ]
}
''',
    )
    write_text(
        dst / "config.gni",
        '''# Copyright (c) 2022 Huawei Device Co., Ltd.

board_arch = "armv7-a"
board_cpu = "cortex-a7"
board_toolchain_type = "clang"
board_fpu = "neon-vfpv4"
''',
    )

    bundle = load_json(dst / "bundle.json")
    bundle["name"] = "@ohos/qemu_armv7a_linux_full_device"
    bundle["description"] = "device part definition for qemu armv7a linux full"
    bundle["segment"]["destPath"] = "device/qemu/arm_virt/linux_full_armv7a"
    component = bundle["component"]
    component["name"] = "qemu_virt_full_armv7a"
    component["subsystem"] = "device_armv7a_virt"
    component["build"]["sub_component"] = [
        "//drivers/peripheral/camera/vdi_base/usb_camera:usb_camera_vdi_impl",
        "//device/qemu/arm_virt/linux_full_armv7a:qemu-armv7a-linux-full-group",
    ]
    dump_json(dst / "bundle.json", bundle)


def create_product(root: Path) -> None:
    src = root / "vendor/ohemu/qemu_arm64_linux_full"
    dst = root / "vendor/ohemu/qemu_armv7a_linux_full"
    copy_owned_tree(src, dst)

    common_src = root / "vendor/ohemu/virt/virt_common.json"
    common_dst = root / "vendor/ohemu/virt/virt_common_armv7a.json"
    common = load_json(common_src)
    for subsystem in common.get("subsystems", []):
        if subsystem.get("subsystem") != "device_arm64_virt":
            continue
        subsystem["subsystem"] = "device_armv7a_virt"
        for component in subsystem.get("components", []):
            if component.get("component") == "qemu_virt_full":
                component["component"] = "qemu_virt_full_armv7a"
        break
    else:
        die(f"expected device_arm64_virt subsystem in {common_src}")
    dump_json(common_dst, common)

    config = load_json(dst / "config.json")
    config["product_name"] = "armv7a_virt"
    config["device_build_path"] = "device/qemu/arm_virt/linux_full_armv7a"
    config["target_cpu"] = "arm"
    config["target_os"] = "ohos"
    config["board"] = "armv7a_virt"
    config["inherit"] = [
        "productdefine/common/inherit/rich.json",
        "productdefine/common/inherit/chipset_common.json",
        "vendor/ohemu/virt/virt_common_armv7a.json",
    ]
    dump_json(dst / "config.json", config)

    bundle_path = dst / "bundle.json"
    bundle = load_json(bundle_path)
    bundle["name"] = "@ohos/qemu_armv7a_linux_full_product"
    bundle["description"] = "product part definition for qemu armv7a linux full"
    bundle["segment"]["destPath"] = "vendor/ohemu/qemu_armv7a_linux_full"
    component = bundle["component"]
    component["name"] = "product_armv7a_virt"
    component["subsystem"] = "product_armv7a_virt"
    component["build"]["sub_component"] = [
        "//vendor/ohemu/qemu_armv7a_linux_full/power_config:power_mode_config"
    ]
    dump_json(bundle_path, bundle)

    power_path = dst / "power_config/BUILD.gn"
    power = replace_all(
        read_text(power_path),
        [
            ("product_arm64_virt", "product_armv7a_virt"),
            ("qemu_arm64_linux_full", "qemu_armv7a_linux_full"),
        ],
    )
    write_text(power_path, power)

    write_text(dst / "qemu_run.sh", armv7a_qemu_run())


def armv7a_qemu_run() -> str:
    return r'''#!/bin/bash

# Experimental armv7a full-system QEMU launcher generated by ohos-qemu.

set -euo pipefail

OHOS_IMG="${OHOS_IMG:-out/armv7a_virt/packages/phone/images}"
DISPLAY_TYPE="${QEMU_DISPLAY:-none}"

ACCEL_SUPPORT=$(qemu-system-arm -accel help 2>&1 | grep "Accelerators supported" || true)
if [ -e /dev/kvm ] && [ -r /dev/kvm ] && echo "$ACCEL_SUPPORT" | grep -q "kvm"; then
    ACCEL_ARGS="-accel kvm"
    echo "KVM acceleration enabled." >&2
else
    ACCEL_ARGS="-accel tcg,thread=multi"
    echo "Hardware acceleration not available, using TCG software emulation." >&2
fi

NET_ARGS=(
    -netdev user,id=net0,hostfwd=tcp::5555-:5555
    -device virtio-net-device,netdev=net0,mac=12:22:33:44:55:67
)

case "${DISPLAY_TYPE}" in
    none)
        DISPLAY_ARGS="-device virtio-gpu-pci,xres=800,yres=500 -display none -monitor none -chardev stdio,id=serial0,signal=off -serial chardev:serial0"
        ;;
    vnc)
        DISPLAY_ARGS="-device virtio-gpu-pci,xres=800,yres=500 -vnc :21"
        echo "Display: VNC on port 5921"
        ;;
    sdl|*)
        DISPLAY_ARGS="-device virtio-gpu-pci,xres=800,yres=500 -display sdl,gl=off"
        echo "Display: SDL"
        ;;
esac

QEMU_CMD="qemu-system-arm ${ACCEL_ARGS} \
-M virt \
-cpu cortex-a7 \
-smp 4 \
-m 4096 \
-kernel ${OHOS_IMG}/zImage \
-initrd ${OHOS_IMG}/ramdisk.img \
${DISPLAY_ARGS} \
-device virtio-mouse-pci \
-device virtio-keyboard-pci \
-k en-us \
-rtc base=localtime,clock=host \
${NET_ARGS[@]} \
-drive if=none,file=${OHOS_IMG}/updater.img,format=raw,id=updater -device virtio-blk-device,drive=updater,serial=updater \
-drive if=none,file=${OHOS_IMG}/system.img,format=raw,id=system -device virtio-blk-device,drive=system,serial=system \
-drive if=none,file=${OHOS_IMG}/vendor.img,format=raw,id=vendor -device virtio-blk-device,drive=vendor,serial=vendor \
-drive if=none,file=${OHOS_IMG}/sys_prod.img,format=raw,id=sys_prod -device virtio-blk-device,drive=sys_prod,serial=sys_prod \
-drive if=none,file=${OHOS_IMG}/chip_prod.img,format=raw,id=chip_prod -device virtio-blk-device,drive=chip_prod,serial=chip_prod \
-drive if=none,file=${OHOS_IMG}/userdata.img,format=raw,id=userdata -device virtio-blk-device,drive=userdata,serial=userdata \
-append \" \
default_boot_device=a003e00.virtio_mmio \
sn=0023456789 \
ip=dhcp \
loglevel=4 \
console=ttyAMA0,115200 \
init=/init ohos.boot.hardware=virt \
root=/dev/ram0 rw \
ohos.required_mount.system=/dev/block/vde@/usr@ext4@ro,barrier=1@wait,required \
ohos.required_mount.vendor=/dev/block/vdd@/vendor@ext4@ro,barrier=1@wait,required \
ohos.required_mount.sys_prod=/dev/block/vdc@/sys_prod@ext4@rw,barrier=1@wait,required \
ohos.required_mount.chip_prod=/dev/block/vdb@/chip_prod@ext4@rw,barrier=1@wait,required \
ohos.required_mount.data=/dev/block/vda@/data@ext4@nosuid,nodev,noatime,barrier=1,data=ordered,noauto_da_alloc@wait,reservedsize=104857600\""

echo "=== QEMU Command ===" >&2
echo "$QEMU_CMD" >&2
echo "====================" >&2
eval "$QEMU_CMD"
'''


def main() -> None:
    if len(sys.argv) != 2:
        die("usage: apply.py OHOS_ROOT")
    root = Path(sys.argv[1]).resolve()
    if not (root / "build.sh").exists():
        die(f"not an OpenHarmony checkout: {root}")

    create_device(root)
    create_product(root)
    ensure_device_gni(root)
    ensure_hardware_group(root)
    ensure_whitelist(root)
    print("armv7a_virt full overlay applied")


if __name__ == "__main__":
    main()
